version: '3.6'
services:
  postgres:
    container_name: postgres_tapir
    image: postgres:13-alpine
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    ports:
      - 54325:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    # Вывод текущих sql запросов в stdout
    command: postgres -c log_statement=all

  flyway:
    container_name: flyway_tapir
    image: flyway/flyway:7.10.0
    entrypoint: flyway -user=docker -password=docker -url=jdbc:postgresql://postgres:5432/docker
    command: migrate
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/migrations:/flyway/sql

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper_tapir
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    container_name: broker_tapir
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  volume_postgres:
