### Create JWT-token
POST {{url}}/token
Content-Type: application/json
Accept: application/json

{
  "name": "whsv26",
  "password": "123456"
}

### Hello world
GET {{url}}/hello-world?whom=whsv26
Accept: application/json

### Delete foo
DELETE {{url}}/foo/5ef7a170-87a2-4c54-be9c-1da9165d90a8
Accept: application/json

### Create foo
POST {{url}}/foo
Content-Type: application/json
Accept: application/json

{
  "a": 999,
  "b": false
}

