### Create JWT-token
POST {{url}}/token
Content-Type: application/json
Accept: application/json

{
  "name": "whsv26",
  "password": "123456"
}

> {%
client.global.set("jwtToken", response.body);
%}

### Get foo
GET {{url}}/foo/{{fooId}}
Authorization: Bearer {{jwtToken}}
Accept: application/json


### Delete foo
DELETE {{url}}/foo/{{fooId}}
Authorization: Bearer {{jwtToken}}
Accept: application/json

### Create foo
POST {{url}}/foo
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwtToken}}

{
  "a": 999,
  "b": false
}

